# Generated by Django 5.2.3 on 2025-06-26 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoptions', '0001_initial'),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionmatch',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat'),
        ),
    ]
