# Generated by Django 5.2.3 on 2025-06-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionpreference',
            name='preferred_breed',
            field=models.CharField(blank=True, choices=[('persian', '페르시안'), ('siamese', '샴'), ('british_shorthair', '브리티시 쇼트'), ('british_longhair', '브리티시 롱'), ('ragdoll', '랙돌'), ('sphynx', '스핑크스'), ('munchkin', '먼치킨'), ('scottish_fold', '스코티시 폴드'), ('russian_blue', '러시안 블루'), ('balinese', '발리니즈'), ('norwegian_forest', '노르웨이 숲')], max_length=50),
        ),
    ]
