# Generated by Django 5.2.3 on 2025-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=100),
        ),
    ]
